# Generated by Django 4.1 on 2024-09-16 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_user_image_url_growthrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
