# Generated by Django 4.1 on 2024-09-19 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_artwork_posted_at_artwork_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarymedia',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='app.diary'),
        ),
    ]
