# Generated by Django 4.1 on 2024-09-26 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_diarymedia_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthrecord',
            name='measurement_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
