# Generated by Django 4.1 on 2024-09-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_diarymedia_media_url_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diary',
            table='diaries',
        ),
        migrations.AlterModelTable(
            name='diarymedia',
            table='diary_media',
        ),
        migrations.AlterModelTable(
            name='stamp',
            table='stamps',
        ),
        migrations.AlterModelTable(
            name='template',
            table='templates',
        ),
    ]
