# Generated by Django 4.1 on 2024-09-14 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_diarymedia_media_url_diarymedia_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.child'),
        ),
    ]
