# Generated by Django 4.1 on 2024-09-15 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.household'),
        ),
    ]
