# Generated by Django 4.1 on 2024-09-17 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_diary_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='posted_at',
        ),
        migrations.AddField(
            model_name='artwork',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
