# Generated by Django 5.1.1 on 2024-09-27 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_growthrecord_measurement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='household',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='app.household'),
            preserve_default=False,
        ),
    ]
